Fix Ed25519 public key point used in test
The 31-byte byte array was incorrect, which would lead to
```
java.lang.IllegalArgumentException: invalid Ed25519 public key data
        at org.bouncycastle.crypto.asymmetric.KeyUtils.isValidEdDSAPublicKey(Unknown Source)
```
even if `java.security.spec.EdECPublicKeySpec` would be supported.

(Also, explicitly use `Ed25519` instead of `EdDSA`.)